### GET all Characters

GET http://localhost:3000/api/characters HTTP/1.1

### GET a single Character

GET http://localhost:3000/api/characters/:name HTTP/1.1

### GET a single user which doesn't exist

GET http://localhost:3000/api/characters/Bobby HTTP/1.1

### Delete a Character
DELETE http://localhost:3000/api/characters/Night King HTTP/1.1


### POST a Character
POST http://localhost:3000/api/characters HTTP/1.1
Content-Type: application/json

{
    "name": "Night King",
    "dateOfBirth": "10.000 BC",
    "dayOfDeath": "305 AC"
}

### PATCH a new Field

PATCH http://localhost:3000/api/characters/Tyrion Lannister HTTP/1.1
Content-Type: application/json

{
    "firstSeen": "Winter is coming"
}

### DELETE a Field

PUT http://localhost:3000/api/characters/Tyrion Lannister HTTP/1.1
Content-Type: application/json

{
    "firstSeen": ""
}